language: node_js
node_js:
  - "8.5.0"
before_install:
  # custom commands before the installation phase
install:
  # install any dependencies required
  - yarn install
before_script:
  # custom commands before the script phase
script:
  # run the build script
  - yarn build
after_script:
  # custom commands after script
after_success:
  # $TRAVIS_TEST_RESULT
  # push public folder content into github pages repository
  - bash updateProduction.sh
